/* Nonlinear SI model: eight states, point masses, absolute angles. */
function liveDerivative(s,gain,pull,forceOverride=null){
 const L=1/6,W=[.2,2/15,1/15],H=W.map(v=>v*L),a=[s[2],s[4],s[6]],w=[s[3],s[5],s[7]];
 const M=Array.from({length:4},()=>Array(4).fill(0));M[0][0]=1;
 let u=forceOverride===null?Math.max(-8,Math.min(8,-gain.reduce((v,k,i)=>v+k*s[i],0))):forceOverride,rhs=[u-.08*s[1],0,0,0];
 for(let i=0;i<3;i++){M[0][i+1]=M[i+1][0]=H[i]*Math.cos(a[i]);rhs[0]+=H[i]*Math.sin(a[i])*w[i]*w[i];rhs[i+1]=9.81*H[i]*Math.sin(a[i]);for(let j=0;j<3;j++){const C=W[Math.max(i,j)]*L*L;M[i+1][j+1]=C*Math.cos(a[i]-a[j]);rhs[i+1]-=C*Math.sin(a[i]-a[j])*w[j]*w[j]}}
 if(pull){let x=s[0],y=0,vx=s[1],vy=0;for(let i=0;i<pull.point;i++){x+=L*Math.sin(a[i]);y+=L*Math.cos(a[i]);vx+=L*Math.cos(a[i])*w[i];vy-=L*Math.sin(a[i])*w[i]}let fx=3*(pull.x-x)-.025*vx,fy=3*(pull.y-y)-.025*vy;const mag=Math.hypot(fx,fy),factor=Math.min(1,.12/Math.max(mag,1e-12));const strength=pull.strength===undefined?1:pull.strength;fx*=factor*strength;fy*=factor*strength;rhs[0]+=fx;for(let i=0;i<pull.point;i++)rhs[i+1]+=L*(Math.cos(a[i])*fx-Math.sin(a[i])*fy)}
 const augmented=M.map((row,i)=>[...row,rhs[i]]);for(let k=0;k<4;k++){let pivot=k;for(let i=k+1;i<4;i++)if(Math.abs(augmented[i][k])>Math.abs(augmented[pivot][k]))pivot=i;[augmented[k],augmented[pivot]]=[augmented[pivot],augmented[k]];const d=augmented[k][k];for(let j=k;j<=4;j++)augmented[k][j]/=d;for(let i=0;i<4;i++)if(i!==k){const factor=augmented[i][k];for(let j=k;j<=4;j++)augmented[i][j]-=factor*augmented[k][j]}}
 return [s[1],augmented[0][4],s[3],augmented[1][4],s[5],augmented[2][4],s[7],augmented[3][4]];
}
function liveFeedback(s,gain,tracking,time){let target=Array(8).fill(0),K=gain,feedforward=0;if(tracking&&time<tracking.times.at(-1)){let i=Math.min(tracking.times.length-2,Math.max(0,Math.floor(time/.01)));while(i>0&&tracking.times[i]>time)i--;while(i<tracking.times.length-2&&tracking.times[i+1]<time)i++;const f=(time-tracking.times[i])/(tracking.times[i+1]-tracking.times[i]);target=target.map((_,j)=>tracking.states[i][j]*(1-f)+tracking.states[i+1][j]*f);K=gain.map((_,j)=>tracking.gains[i][j]*(1-f)+tracking.gains[i+1][j]*f);feedforward=tracking.forces[i]*(1-f)+tracking.forces[i+1]*f}const error=s.map((v,i)=>v-target[i]);for(const i of [2,4,6])error[i]=Math.atan2(Math.sin(error[i]),Math.cos(error[i]));const taper=(v,inner,outer)=>{const z=Math.max(0,Math.min(1,(Math.abs(v)-inner)/(outer-inner)));return 1-z*z*(3-2*z)};let authority=taper(error[0],.5,1)*taper(error[1],1,2);for(const i of [2,4,6])authority*=taper(error[i],.22,.45)*taper(error[i+1],3,6);const brake=Math.max(-2,Math.min(2,-4*s[1]-2*s[0]));return{force:authority*Math.max(-8,Math.min(8,feedforward-K.reduce((v,k,i)=>v+k*error[i],0)))+(1-authority)*brake,authority}}
function liveControl(s,gain,tracking,time){return liveFeedback(s,gain,tracking,time).force}

function liveStep(s,gain,pull,dt,tracking=null,time=0,push=false){const rhs=(state,t)=>liveDerivative(state,gain,pull,liveControl(state,gain,tracking,t)+(push&&t>=4&&t<4.2?3:0)),add=(v,k)=>s.map((x,i)=>x+k*v[i]),a=rhs(s,time),b=rhs(add(a,dt/2),time+dt/2),c=rhs(add(b,dt/2),time+dt/2),d=rhs(add(c,dt),time+dt);return s.map((x,i)=>x+dt*(a[i]+2*b[i]+2*c[i]+d[i])/6)}
if(typeof module!=='undefined')module.exports={liveDerivative,liveStep,liveControl,liveFeedback};
