"""Build an offline near-upright comparison, preserving the original demo."""
import json
from pathlib import Path
import numpy as np
from massive_rods import Model
from triple_pendulum import Q,R
ROOT=Path(__file__).resolve().parents[1]
out=ROOT/'results/massive_rods';out.mkdir(exist_ok=True)
data={};summary={}
for label,mass in [('point',0),('massive',.01)]:
 m=Model(mass);K,P=m.controller();A,B=m.linear_model();reach=np.column_stack([np.linalg.matrix_power(A,i)@B for i in range(8)]);reach/=np.linalg.norm(reach,axis=0)
 residual=A.T@P+P@A-P@B@B.T@P/R+np.diag(Q)
 summary[label]={'rod_mass_kg':mass,'suspended_mass_kg':float(sum(m.points)+sum(m.rods)),'K':K.tolist(),'controllability_rank':int(np.linalg.matrix_rank(reach)),'max_real_pole':float(np.linalg.eigvals(A-B@K[None,:]).real.max()),'relative_riccati_residual':float(np.linalg.norm(residual)/np.linalg.norm(np.diag(Q))),'cases':{}}
 data[label]={}
 for case in ['aligned','opposed','push']:
  dt=.00125 if case=='opposed' else .0025
  rows,met=m.simulate(case,dt=dt);fine,fmet=m.simulate(case,dt=dt/2)
  met['integration_step_s']=dt
  n=min(len(rows),len(fine[::2]));met['refinement_max_state_difference']=float(np.max(abs(rows[:n,1:9]-fine[::2][:n,1:9])))
  assert met['status']==fmet['status']
  assert met['refinement_max_state_difference']<.002,(label,case,met)
  met['refined_end_s']=fmet['end_s'];summary[label]['cases'][case]=met
  np.savetxt(out/f'{label}_{case}.csv',rows,delimiter=',',header='time,x,v,theta1,omega1,theta2,omega2,theta3,omega3,force,push',comments='')
  display=rows[::8].tolist()
  if display[-1][0]!=rows[-1,0]:display.append(rows[-1].tolist())
  data[label][case]={'rows':display,'metrics':met}
(out/'summary.json').write_text(json.dumps(summary,indent=2))
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Triple pendulum — massive rods</title><style>body{margin:0;background:#eef4f6;color:#193746;font:17px/1.6 system-ui}main{max-width:1150px;margin:30px auto;padding:24px}h1{line-height:1.15}section,.controls{background:white;border-radius:18px;padding:22px;margin:18px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}canvas{width:100%;height:350px;background:#f6f9fb;border-radius:14px}button,select{font:inherit;padding:9px;border:1px solid #bdd1d9;border-radius:8px}button{background:#183747;color:white;cursor:pointer}input{width:100%}.note{border-left:4px solid #138a85;padding:14px;background:#e0f1ee}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:8px;text-align:left;border-bottom:1px solid #ddd}.scroll{overflow:auto}a{color:#087d76}@media(max-width:700px){.grid{grid-template-columns:1fr}main{padding:12px}}</style><main>
<a href="triple.html">Original triple-pendulum demo</a> · <a href="massive-swingup.html">New: massive-rod swing-up</a><h1>What changes when the rods have mass?</h1><p>Stage 1 · Stabilisation near the upright equilibrium</p><p class="note">Three uniform rods, <b>10 g each</b>, added to the existing endpoint masses. Suspended mass: <b>200 → 230 g</b>. Only the cart is motorised; force remains limited to ±8 N. Each model receives its own recalculated LQR.</p>
<div class="controls"><select id="case"><option value="aligned">Aligned lean · +1° / +1° / +1°</option><option value="opposed">Opposing lean · +1° / −1° / +1°</option><option value="push">External push · 3 N from 4 to 4.2 s</option></select> <button id="play">Play</button> <button id="restart">Restart</button><p id="time"></p><input id="slider" aria-label="Simulation time" type="range" min="0" max="12" step=".01" value="0"></div>
<div class="grid"><section><h2>Massless rods</h2><canvas id="point"></canvas><p id="point-status"></p></section><section><h2>Massive rods · 10 g each</h2><canvas id="massive"></canvas><p id="massive-status"></p></section></div>
<section><h2>Measured simulation outcomes</h2><div class="scroll"><table><thead><tr><th>Model</th><th>Trial</th><th>Status</th><th>Settling (s)</th><th>Peak force (N)</th></tr></thead><tbody id="table"></tbody></table></div><p>Settling requires |x| ≤ 0.02 m, |v| ≤ 0.03 m/s, each angle ≤1° and each angular speed ≤0.05 rad/s, for the rest of the 12 s record with at least 1 s remaining. Push settling is absolute time from simulation start. Trials stop at 60° tilt or ±2 m travel; these are cutoffs, not collisions. Failure cases are retained.</p></section>
<section><h2>The calculations behind the change</h2><p>Each rod contributes translational kinetic energy of its centre of mass, rotational kinetic energy, and gravitational potential energy:</p><p><i>T</i><sub>rod</sub> = ½m|v<sub>centre</sub>|² + ½Iω² &nbsp; · &nbsp; I = mL²/12 &nbsp; · &nbsp; V<sub>rod</sub> = mg y<sub>centre</sub></p><p>The coupled equations retain the form M(q)q̈ = f(q,q̇,u). Both the mass matrix and gravity terms change. The linearisation and Riccati equation are recomputed using the same Q and R, so controller gains change with the model.</p><p>The point masses remain 0.2/3 kg each; rod lengths remain 1/6 m; cart mass is 0.8 kg. Cart viscous friction is 0.08 N·s/m; hinges remain frictionless. Rods are rigid, with uniformly distributed mass. Sensing and force actuation remain ideal. This comparison changes total mass as well as mass distribution.</p><h2>What has been verified?</h2><p>Zero rod mass recovers the original equations. Independently assembled rigid-body energies match the matrix model; mechanical power balance and finite-difference linearisation are checked. All six trials are repeated with the integration step halved. <a href="../results/massive_rods/summary.json">Numerical checks and gains</a>.</p><p class="note">This page plays saved nonlinear simulations, with interpolation only for display. Mouse manipulation is not included here. The separate massive-rod swing-up is linked above. The original page remains a separate massless-rod model.</p><p>AI-assisted educational simulation; no hardware validation or global stability claim.</p></section></main><script>
const data=DATA;let time=0,playing=false,prev=null;const select=document.getElementById('case'),slider=document.getElementById('slider');
function sample(rows,t){if(t<=0)return rows[0];if(t>=rows.at(-1)[0])return rows.at(-1);let lo=0,hi=rows.length-1;while(hi-lo>1){let m=(lo+hi)>>1;if(rows[m][0]<=t)lo=m;else hi=m}const f=(t-rows[lo][0])/(rows[hi][0]-rows[lo][0]);return rows[lo].map((v,i)=>v+f*(rows[hi][i]-v))}
function draw(){document.getElementById('time').textContent=`Time: ${time.toFixed(2)} s`;slider.value=time;for(const key of ['point','massive']){const exp=data[key][select.value],s=sample(exp.rows,time),c=document.getElementById(key),w=c.clientWidth,h=350,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const scale=Math.min(430,(w-40)/1.2),origin=w/2,x=origin+s[1]*scale,y=285;ctx.strokeStyle='#bccfd7';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(10,y+25);ctx.lineTo(w-10,y+25);ctx.stroke();ctx.fillStyle='#193746';ctx.fillRect(x-22,y-8,44,24);let px=x,py=y;for(let j=0;j<3;j++){const a=s[3+2*j],nx=px+scale/6*Math.sin(a),ny=py-scale/6*Math.cos(a);ctx.strokeStyle=['#138b85','#7a61b4','#dc902e'][j];ctx.lineWidth=key==='massive'?9:4;ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(nx,ny);ctx.stroke();ctx.beginPath();ctx.arc(nx,ny,7,0,2*Math.PI);ctx.fillStyle=ctx.strokeStyle;ctx.fill();px=nx;py=ny}ctx.fillStyle='#193746';ctx.font='14px system-ui';ctx.fillText(`x ${s[1].toFixed(3)} m · force ${s[9].toFixed(2)} N`,14,25);document.getElementById(key+'-status').textContent=exp.metrics.status!=='completed'&&time>=exp.metrics.end_s?`Stopped at ${exp.metrics.end_s.toFixed(3)} s: ${exp.metrics.status.replaceAll('_',' ')}.`:'Angles: '+[s[3],s[5],s[7]].map(v=>(v*180/Math.PI).toFixed(2)+'°').join(' / ')}}
function reset(){playing=false;time=0;prev=null;document.getElementById('play').textContent='Play';draw()}
document.getElementById('play').onclick=()=>{if(time>=12)time=0;playing=!playing;prev=null;document.getElementById('play').textContent=playing?'Pause':'Play'};document.getElementById('restart').onclick=reset;select.onchange=reset;slider.oninput=()=>{playing=false;time=Number(slider.value);document.getElementById('play').textContent='Play';draw()};window.addEventListener('resize',draw);
function frame(now){if(playing&&prev!==null){time=Math.min(12,time+Math.max(0,Math.min(.05,(now-prev)/1000)));draw();if(time===12){playing=false;document.getElementById('play').textContent='Play'}}prev=now;requestAnimationFrame(frame)}
for(const key of ['point','massive'])for(const [trial,e] of Object.entries(data[key])){const m=e.metrics;document.getElementById('table').innerHTML+=`<tr><td>${key==='point'?'Massless':'Massive'}</td><td>${trial}</td><td>${m.status}</td><td>${m.settling_s===null?'Not settled':m.settling_s.toFixed(3)}</td><td>${m.peak_force_N.toFixed(3)}</td></tr>`}draw();requestAnimationFrame(frame);
</script></html>'''
(ROOT/'visualization/massive-rods.html').write_text(html.replace('DATA',json.dumps(data)))
print(json.dumps(summary,indent=2))
